import { writeFile } from 'node:fs/promises';

import { REQUIRED_SOURCE_LAYERS } from '../basemap/style.js';
import type { SourceLayerInput } from '../mvt/encode.js';
import { encodeTilePyramid } from '../mvt/encode.js';
import { buildPmtilesArchive } from '../pmtiles/writer.js';
import {
  FIXTURE_CENTER,
  FIXTURE_DETAIL_BOUNDS,
  FIXTURE_REGION_BOUNDS,
  fixtureBoundaryLayer,
  fixtureBuildingLayer,
  fixturePlaceLayer,
  fixtureTransportationLayer,
  fixtureWaterLayer,
} from './fixture-features.js';
import type { BasemapBuildRequest, BasemapBuildResult, BasemapTileBuilder } from './types.js';

export const SYNTHETIC_BUILDER_ID = 'synthetic';
export const SYNTHETIC_SCHEMA = { name: 'atlas-os-fixture', version: '1' } as const;
export const SYNTHETIC_MIN_ZOOM = 0;
export const SYNTHETIC_MAX_ZOOM = 13;
const DETAIL_MIN_ZOOM = 9;

/**
 * Attribution for the generated fixture.
 *
 * It credits nothing real because it contains nothing real, and it says so where a viewer will
 * see it: the fixture must never be mistaken for a map of an actual territory.
 */
export const SYNTHETIC_ATTRIBUTION =
  'Synthetic development fixture &mdash; not a map of any territory';

function sourceLayers(): readonly SourceLayerInput[] {
  return [
    { features: fixtureWaterLayer(), maxZoom: SYNTHETIC_MAX_ZOOM, minZoom: 0, name: 'water' },
    { features: fixtureBoundaryLayer(), maxZoom: SYNTHETIC_MAX_ZOOM, minZoom: 0, name: 'boundary' },
    {
      features: fixtureTransportationLayer(),
      maxZoom: SYNTHETIC_MAX_ZOOM,
      minZoom: 2,
      name: 'transportation',
    },
    { features: fixturePlaceLayer(), maxZoom: SYNTHETIC_MAX_ZOOM, minZoom: 2, name: 'place' },
    {
      features: fixtureBuildingLayer(),
      maxZoom: SYNTHETIC_MAX_ZOOM,
      minZoom: 12,
      name: 'building',
    },
  ];
}

/**
 * Builds a deterministic basemap archive from generated geometry.
 *
 * This is the developer and test path. It needs no OpenStreetMap extract, no Java runtime and no
 * network, yet emits a genuine PMTiles archive of MVT tiles carrying the same source layers as
 * the production build, so every downstream stage is tested against real artifacts.
 */
export class SyntheticTileBuilder implements BasemapTileBuilder {
  readonly id = SYNTHETIC_BUILDER_ID;

  async build(request: BasemapBuildRequest): Promise<BasemapBuildResult> {
    const tiles = encodeTilePyramid(sourceLayers(), {
      maxZoom: SYNTHETIC_MAX_ZOOM,
      windows: [
        {
          bounds: FIXTURE_REGION_BOUNDS,
          maxZoom: DETAIL_MIN_ZOOM - 1,
          minZoom: SYNTHETIC_MIN_ZOOM,
        },
        { bounds: FIXTURE_DETAIL_BOUNDS, maxZoom: SYNTHETIC_MAX_ZOOM, minZoom: DETAIL_MIN_ZOOM },
      ],
    });

    const archive = buildPmtilesArchive(tiles, {
      bounds: FIXTURE_REGION_BOUNDS,
      center: {
        latitude: FIXTURE_CENTER.latitude,
        longitude: FIXTURE_CENTER.longitude,
        zoom: FIXTURE_CENTER.zoom,
      },
      maxZoom: SYNTHETIC_MAX_ZOOM,
      // Written into the archive itself, so snapshot validation can verify the style and the
      // manifest against what the archive declares rather than against a builder constant.
      metadata: {
        attribution: SYNTHETIC_ATTRIBUTION,
        description: 'Synthetic basemap fixture generated by atlas-os.',
        name: SYNTHETIC_SCHEMA.name,
        vector_layers: REQUIRED_SOURCE_LAYERS.map((id) => ({
          id,
          maxzoom: SYNTHETIC_MAX_ZOOM,
          minzoom: SYNTHETIC_MIN_ZOOM,
        })),
        version: SYNTHETIC_SCHEMA.version,
      },
      minZoom: SYNTHETIC_MIN_ZOOM,
    });

    await writeFile(request.archivePath, archive);

    return {
      attribution: SYNTHETIC_ATTRIBUTION,
      bounds: FIXTURE_REGION_BOUNDS,
      // Generated from code, so there is no operator-supplied input to record.
      inputs: [],
      center: {
        latitude: FIXTURE_CENTER.latitude,
        longitude: FIXTURE_CENTER.longitude,
        zoom: FIXTURE_CENTER.zoom,
      },
      maxZoom: SYNTHETIC_MAX_ZOOM,
      minZoom: SYNTHETIC_MIN_ZOOM,
      schema: { name: SYNTHETIC_SCHEMA.name, version: SYNTHETIC_SCHEMA.version },
      sourceLayers: [...REQUIRED_SOURCE_LAYERS],
      tool: { name: 'atlas-os-synthetic', version: '1' },
    };
  }
}
