pid /tmp/nginx.pid;
error_log /dev/stderr notice;

events {
  worker_connections 512;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;
  client_body_temp_path /tmp/client_temp;

  server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
      access_log off;
      add_header Content-Type text/plain;
      return 200 "ok\n";
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
